---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: node-mongo
  labels:
    app: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: node-mongo
  labels:
    app: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.2.8
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: volume-01
              mountPath: /data
          resources:
            limits:
              cpu: 1
              memory: 500Mi
      volumes:
        - name: volume-01
          persistentVolumeClaim:
            claimName: pv-claim-01
