apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-01
  labels:
    app: volume-01
    type: local
spec:
  storageClassName: ""
  claimRef:
    name: pv-claim-01
    namespace: node-mongo
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/pv-volume-01"