apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-01
  namespace: node-mongo
  labels:
    app: volume-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi