---
apiVersion: v1
kind: Service
metadata:
  name: service-node
  namespace: node-mongo
  labels:
    name: node
spec:
  type: ClusterIP
  selector:
    name: node
  ports:
    - name: "8000"
      port: 8000
      protocol: TCP
      targetPort: node
    - name: "9229"
      port: 9229
      protocol: TCP
      targetPort: node
status:
  loadBalancer: {}
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-node
  namespace: node-mongo
  labels:
    name: node
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: node
    spec:
      containers:
        - env:
            - name: CONNECTIONSTRING
              value: mongodb://mongo:27017/notes
            - name: SERVER_PORT
              value: "8000"
          image: jsgiraldoh/node-docker
          name: node
          ports:
            - containerPort: 8000
            - containerPort: 9229
          resources: {}