---
apiVersion: v1
kind: Service
metadata:
  name: service-node
  namespace: node-mongo
  labels:
    name: node
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    name: node
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-node
  namespace: node-mongo
  labels:
    name: node
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: node
    spec:
      containers:
        - env:
            - name: CONNECTIONSTRING
              value: mongodb://mongo:27017/notes
            - name: SERVER_PORT
              value: "3000"
          image: pedrodotmc/unir-containers-activity3-node-mongo:1.0.0
          name: node
          ports:
            - containerPort: 3000
            - containerPort: 9229
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
