apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  type: ClusterIP
  selector:
    app: node
  ports:
    - name: "8000"
      port: 8000
      protocol: TCP
      targetPort: node
    - name: "9229"
      port: 9229
      protocol: TCP
      targetPort: node
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - args:
            - npm
            - run
            - debug
          env:
            - name: CONNECTIONSTRING
              value: mongodb://mongo:27017/notes
            - name: SERVER_PORT
              value: "8000"
          image: jsgiraldoh/node-docker
          name: node
          ports:
            - containerPort: 8000
            - containerPort: 9229
          resources: {}
          volumeMounts:
            - name: volume-02
              mountPath: /app
      volumes:
        - name: volume-02
          persistentVolumeClaim:
            claimName: pv-claim-02