apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-02
  labels:
    app: volume-02
    type: local
spec:
  storageClassName: ""
  claimRef:
    name: pv-claim-02    
    namespace: node-mongo
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/pv-volume-02"