apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-02
  namespace: node-mongo
  labels:
    app: volume-02
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi